-- 1. 회원
CREATE TABLE users (
                       id           BIGINT AUTO_INCREMENT PRIMARY KEY,
                       email        VARCHAR(100) NOT NULL UNIQUE,
                       password     VARCHAR(255) NOT NULL,
                       name         VARCHAR(50)  NOT NULL,
                       phone        VARCHAR(20),
                       created_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
                       updated_at   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 2. 상품 카테고리
CREATE TABLE categories (
                            id          INT AUTO_INCREMENT PRIMARY KEY,
                            name        VARCHAR(50) NOT NULL UNIQUE,
                            description VARCHAR(255)
) ENGINE=InnoDB;

-- 3. 상품
CREATE TABLE products (
                          id           BIGINT AUTO_INCREMENT PRIMARY KEY,
                          category_id  INT,
                          name         VARCHAR(100) NOT NULL,
                          description  TEXT,
                          price        DECIMAL(10,2) NOT NULL,
                          stock        INT DEFAULT 0,
                          created_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
                          updated_at   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                          FOREIGN KEY (category_id) REFERENCES categories(id)
) ENGINE=InnoDB;

-- 4. 주문
CREATE TABLE orders (
                        id          BIGINT AUTO_INCREMENT PRIMARY KEY,
                        user_id     BIGINT NOT NULL,
                        status      ENUM('PENDING','PAID','SHIPPED','CANCELLED') DEFAULT 'PENDING',
                        total_price DECIMAL(10,2) DEFAULT 0,
                        created_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
                        updated_at  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                        FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB;

-- 5. 주문 아이템
CREATE TABLE order_items (
                             id         BIGINT AUTO_INCREMENT PRIMARY KEY,
                             order_id   BIGINT NOT NULL,
                             product_id BIGINT NOT NULL,
                             quantity   INT NOT NULL,
                             price      DECIMAL(10,2) NOT NULL,
                             FOREIGN KEY (order_id)  REFERENCES orders(id)   ON DELETE CASCADE,
                             FOREIGN KEY (product_id) REFERENCES products(id)
) ENGINE=InnoDB;





SET FOREIGN_KEY_CHECKS = 0;


TRUNCATE TABLE products;

SET FOREIGN_KEY_CHECKS = 1;


INSERT INTO categories (name, description) VALUES
                                               ('Electronics', 'Electronic devices such as smartphones, laptops, and accessories'),
                                               ('Clothing', 'Men and women clothing, fashion, and accessories'),
                                               ('Books', 'Books, e-books, and stationery'),
                                               ('Home & Kitchen', 'Home appliances, kitchenware, and household items'),
                                               ('Sports', 'Sporting goods, sportswear, and equipment'),
                                               ('Toys & Games', 'Toys, board games, and children products'),
                                               ('Beauty', 'Cosmetics, skincare, and personal care products'),
                                               ('Automotive', 'Car accessories, tools, and automotive parts'),
                                               ('Health', 'Health products, supplements, and wellness items'),
                                               ('Jewelry', 'Rings, necklaces, bracelets, and watches'),
                                               ('Garden', 'Gardening tools, plants, and outdoor items'),
                                               ('Pet Supplies', 'Pet food, toys, and accessories'),
                                               ('Office Supplies', 'Stationery, office equipment, and organizers'),
                                               ('Footwear', 'Shoes, boots, sandals, and sports shoes'),
                                               ('Bags', 'Handbags, backpacks, and luggage'),
                                               ('Music', 'Musical instruments, records, and audio devices'),
                                               ('Video Games', 'Gaming consoles, video games, and accessories'),
                                               ('Baby Products', 'Baby clothes, toys, and care items'),
                                               ('Furniture', 'Home furniture, office furniture, and decor'),
                                               ('Groceries', 'Food, beverages, and household grocery items');



INSERT INTO products (category_id, name, description, price, stock) VALUES
                                                                        (1, 'Smartphone X200', 'Latest smartphone with 6.5 inch display', 699.99, 50),
                                                                        (1, 'Laptop Pro 15', 'High performance laptop with 16GB RAM', 1299.99, 30),
                                                                        (1, 'Wireless Earbuds', 'Bluetooth earbuds with noise cancellation', 99.99, 100),
                                                                        (1, 'Smartwatch Series 5', 'Fitness tracking smartwatch', 199.99, 75),
                                                                        (1, '4K LED TV 55 inch', 'Ultra HD television with smart features', 799.99, 20),
                                                                        (2, 'Men T-Shirt Classic', 'Cotton t-shirt in various colors', 19.99, 200),
                                                                        (2, 'Women Dress Summer', 'Lightweight summer dress', 39.99, 150),
                                                                        (2, 'Men Jeans Slim Fit', 'Denim jeans for men', 49.99, 120),
                                                                        (2, 'Women Jacket', 'Warm jacket for winter', 89.99, 80),
                                                                        (2, 'Unisex Hoodie', 'Comfortable hoodie for all seasons', 29.99, 180),
                                                                        (3, 'Novel: The Great Adventure', 'Fiction novel about adventures', 14.99, 250),
                                                                        (3, 'Science Book: Physics Basics', 'Introduction to physics', 24.99, 100),
                                                                        (3, 'Cookbook: Easy Recipes', 'Simple recipes for daily meals', 19.99, 80),
                                                                        (3, 'Children Book: Fun Tales', 'Illustrated storybook for kids', 9.99, 300),
                                                                        (3, 'Notebook A5', 'Lined notebook for school and office', 4.99, 400),
                                                                        (4, 'Blender Pro 1000', 'High power kitchen blender', 59.99, 60),
                                                                        (4, 'Coffee Maker Deluxe', 'Automatic coffee machine', 79.99, 50),
                                                                        (4, 'Vacuum Cleaner 2000W', 'Powerful home vacuum cleaner', 129.99, 40),
                                                                        (4, 'Microwave Oven 25L', 'Compact microwave oven', 89.99, 70),
                                                                        (4, 'Knife Set Stainless', 'Professional kitchen knife set', 49.99, 90),
                                                                        (5, 'Yoga Mat Pro', 'Non-slip yoga mat', 29.99, 100),
                                                                        (5, 'Football Official', 'Standard size football', 24.99, 150),
                                                                        (5, 'Tennis Racket', 'Lightweight tennis racket', 89.99, 60),
                                                                        (5, 'Running Shoes', 'Comfortable running shoes', 59.99, 80),
                                                                        (5, 'Dumbbell Set', 'Adjustable dumbbells for strength training', 79.99, 50),
                                                                        (6, 'Building Blocks Set', 'Educational toy for kids', 39.99, 120),
                                                                        (6, 'Puzzle 1000 pieces', 'Challenging jigsaw puzzle', 19.99, 200),
                                                                        (6, 'Board Game: Adventure Quest', 'Family board game', 29.99, 80),
                                                                        (6, 'Toy Car Set', 'Set of 5 miniature cars', 14.99, 150),
                                                                        (6, 'Stuffed Animal Bear', 'Soft toy for children', 9.99, 180),
                                                                        (7, 'Lipstick Red', 'Long lasting red lipstick', 19.99, 100),
                                                                        (7, 'Face Cream', 'Moisturizing facial cream', 29.99, 70),
                                                                        (7, 'Perfume Eau de Toilette', 'Floral scent perfume', 49.99, 50),
                                                                        (7, 'Shampoo Anti-Dandruff', 'Cleansing shampoo for daily use', 12.99, 200),
                                                                        (7, 'Makeup Brush Set', 'Professional brush kit', 24.99, 150),
                                                                        (8, 'Car Vacuum Cleaner', 'Portable car vacuum', 39.99, 60),
                                                                        (8, 'Car Seat Cover', 'Universal car seat cover', 29.99, 100),
                                                                        (8, 'Car GPS Navigator', 'GPS device with real-time updates', 99.99, 40),
                                                                        (8, 'Car Tool Kit', 'Set of essential car tools', 49.99, 50),
                                                                        (8, 'Dash Cam HD', 'High-definition dashboard camera', 79.99, 30),
                                                                        (9, 'Vitamin C Supplement', 'Daily vitamin supplement', 14.99, 200),
                                                                        (9, 'Protein Powder', 'Whey protein for muscle building', 39.99, 120),
                                                                        (9, 'First Aid Kit', 'Compact first aid kit', 19.99, 150),
                                                                        (9, 'Yoga Ball', 'Stability exercise ball', 24.99, 100),
                                                                        (9, 'Health Tracker', 'Monitor heart rate and steps', 49.99, 80),
                                                                        (10, 'Gold Necklace', '18k gold necklace', 199.99, 20),
                                                                        (10, 'Silver Ring', '925 silver ring with stone', 49.99, 50),
                                                                        (10, 'Wrist Watch Classic', 'Analog wristwatch', 99.99, 30),
                                                                        (10, 'Bracelet Charm', 'Fashionable charm bracelet', 29.99, 100),
                                                                        (10, 'Earrings Set', 'Pair of earrings', 19.99, 150);





INSERT INTO orders (user_id, status, total_price) VALUES
                                                      (1, 'PAID', 149.98),
                                                      (2, 'PENDING', 59.99),
                                                      (3, 'SHIPPED', 79.97),
                                                      (4, 'CANCELLED', 0.00),
                                                      (5, 'PAID', 199.95),
                                                      (6, 'PAID', 49.99),
                                                      (7, 'PENDING', 129.98),
                                                      (8, 'SHIPPED', 59.98),
                                                      (9, 'PAID', 89.97),
                                                      (10, 'PAID', 299.95),
                                                      (11, 'PENDING', 39.99),
                                                      (12, 'SHIPPED', 159.96),
                                                      (13, 'PAID', 49.99),
                                                      (14, 'CANCELLED', 0.00),
                                                      (15, 'PAID', 99.98),
                                                      (16, 'PENDING', 74.97),
                                                      (17, 'PAID', 199.95),
                                                      (18, 'SHIPPED', 59.98),
                                                      (19, 'PAID', 129.97),
                                                      (20, 'PENDING', 49.99),
                                                      (1, 'PAID', 89.95),
                                                      (2, 'SHIPPED', 149.97),
                                                      (3, 'PENDING', 59.99),
                                                      (4, 'PAID', 199.95),
                                                      (5, 'SHIPPED', 79.97),
                                                      (6, 'PAID', 129.98),
                                                      (7, 'PENDING', 59.98),
                                                      (8, 'PAID', 49.99),
                                                      (9, 'SHIPPED', 199.95),
                                                      (10, 'PENDING', 99.97),
                                                      (11, 'PAID', 149.98),
                                                      (12, 'SHIPPED', 79.97),
                                                      (13, 'PAID', 59.99),
                                                      (14, 'CANCELLED', 0.00),
                                                      (15, 'PAID', 199.95),
                                                      (16, 'PENDING', 49.99),
                                                      (17, 'SHIPPED', 129.97),
                                                      (18, 'PAID', 89.98),
                                                      (19, 'PENDING', 79.97),
                                                      (20, 'SHIPPED', 149.95),
                                                      (1, 'PAID', 59.99),
                                                      (2, 'PAID', 99.97),
                                                      (3, 'SHIPPED', 149.98),
                                                      (4, 'PENDING', 49.99),
                                                      (5, 'PAID', 199.95),
                                                      (6, 'SHIPPED', 129.97),
                                                      (7, 'PAID', 79.99),
                                                      (8, 'PENDING', 59.98),
                                                      (9, 'PAID', 199.95),
                                                      (10, 'SHIPPED', 149.97),
                                                      (11, 'PAID', 89.98),
                                                      (12, 'PENDING', 49.99);





INSERT INTO order_items (order_id, product_id, quantity, price) VALUES
                                                                    (42, 37, 2, 315.7),
                                                                    (8, 43, 2, 367.13),
                                                                    (20, 34, 3, 603.18),
                                                                    (49, 20, 2, 466.12),
                                                                    (13, 15, 2, 449.1),
                                                                    (29, 18, 1, 654.58),
                                                                    (14, 4, 2, 141.7),
                                                                    (11, 5, 1, 436.22),
                                                                    (29, 27, 3, 490.6),
                                                                    (34, 31, 1, 384.31),
                                                                    (25, 31, 2, 230.88),
                                                                    (47, 15, 1, 276.54),
                                                                    (45, 16, 1, 378.53),
                                                                    (14, 19, 1, 279.31),
                                                                    (28, 43, 2, 87.76),
                                                                    (46, 38, 2, 445.14),
                                                                    (44, 13, 2, 278.82),
                                                                    (9, 40, 1, 91.31),
                                                                    (5, 29, 1, 318.08),
                                                                    (42, 42, 1, 232.76),
                                                                    (33, 42, 1, 516.6),
                                                                    (18, 13, 1, 416.12),
                                                                    (19, 38, 1, 193.61),
                                                                    (10, 19, 2, 202.53),
                                                                    (44, 40, 2, 680.14),
                                                                    (35, 49, 2, 448.42),
                                                                    (8, 47, 1, 561.49),
                                                                    (27, 11, 2, 149.37),
                                                                    (5, 11, 2, 17.69),
                                                                    (42, 5, 1, 683.36),
                                                                    (15, 35, 2, 48.88),
                                                                    (43, 48, 1, 655.7),
                                                                    (15, 2, 1, 26.65),
                                                                    (49, 25, 3, 217.08),
                                                                    (18, 46, 1, 364.86),
                                                                    (31, 50, 2, 538.1),
                                                                    (40, 27, 3, 128.59),
                                                                    (10, 45, 1, 154.65),
                                                                    (47, 43, 2, 622.13),
                                                                    (49, 13, 2, 41.9),
                                                                    (15, 38, 2, 368.32),
                                                                    (8, 36, 3, 15.75),
                                                                    (14, 48, 3, 622.26),
                                                                    (19, 15, 2, 65.12),
                                                                    (12, 3, 3, 623.07),
                                                                    (22, 37, 1, 437.4),
                                                                    (46, 26, 3, 242.15),
                                                                    (32, 42, 2, 441.9),
                                                                    (36, 47, 3, 28.95),
                                                                    (16, 23, 3, 567.1),
                                                                    (23, 43, 3, 504.02),
                                                                    (1, 31, 3, 444.57),
                                                                    (52, 9, 2, 236.37),
                                                                    (45, 12, 2, 582.69),
                                                                    (17, 35, 2, 116.24),
                                                                    (34, 10, 3, 302.8),
                                                                    (9, 45, 2, 507.0),
                                                                    (16, 41, 1, 22.06),
                                                                    (11, 36, 2, 333.34),
                                                                    (47, 46, 2, 534.59),
                                                                    (8, 44, 1, 108.93),
                                                                    (20, 50, 2, 205.02),
                                                                    (13, 32, 1, 129.72),
                                                                    (18, 47, 3, 613.03),
                                                                    (39, 43, 2, 643.62),
                                                                    (47, 42, 3, 545.87),
                                                                    (32, 37, 2, 165.21),
                                                                    (38, 20, 1, 311.57),
                                                                    (17, 33, 2, 582.05),
                                                                    (14, 26, 3, 139.44),
                                                                    (6, 39, 1, 99.09),
                                                                    (52, 39, 1, 457.99),
                                                                    (35, 23, 1, 525.87),
                                                                    (31, 8, 2, 593.31),
                                                                    (52, 45, 1, 319.91),
                                                                    (46, 15, 3, 611.08),
                                                                    (31, 8, 2, 251.69),
                                                                    (14, 47, 1, 586.51),
                                                                    (30, 34, 1, 527.58),
                                                                    (48, 27, 1, 172.83),
                                                                    (15, 10, 3, 127.9),
                                                                    (48, 26, 2, 110.85),
                                                                    (21, 29, 1, 484.43),
                                                                    (24, 19, 2, 566.93),
                                                                    (50, 15, 1, 665.2),
                                                                    (22, 7, 1, 442.21),
                                                                    (46, 37, 2, 647.5),
                                                                    (7, 30, 3, 678.61),
                                                                    (50, 17, 2, 651.38),
                                                                    (16, 36, 2, 478.18),
                                                                    (6, 47, 2, 217.5),
                                                                    (36, 32, 3, 446.25),
                                                                    (12, 4, 2, 170.52),
                                                                    (4, 47, 3, 430.84),
                                                                    (46, 23, 3, 667.37),
                                                                    (23, 3, 1, 507.53),
                                                                    (31, 6, 3, 285.22),
                                                                    (41, 16, 3, 96.41),
                                                                    (22, 10, 1, 466.77),
                                                                    (47, 15, 2, 56.49),
                                                                    (45, 12, 2, 365.98),
                                                                    (8, 3, 3, 643.72),
                                                                    (35, 38, 3, 676.2),
                                                                    (41, 12, 1, 586.74),
                                                                    (20, 7, 1, 470.56),
                                                                    (44, 45, 2, 108.6),
                                                                    (46, 27, 3, 540.91),
                                                                    (45, 2, 1, 121.26),
                                                                    (4, 24, 1, 89.41),
                                                                    (23, 29, 2, 447.85),
                                                                    (23, 41, 3, 60.93),
                                                                    (32, 32, 2, 521.55),
                                                                    (47, 24, 2, 276.13),
                                                                    (48, 39, 1, 536.47),
                                                                    (11, 9, 3, 20.4),
                                                                    (34, 32, 2, 238.07),
                                                                    (11, 16, 1, 261.41),
                                                                    (50, 6, 1, 500.07),
                                                                    (40, 25, 3, 67.98),
                                                                    (31, 44, 3, 598.17),
                                                                    (7, 28, 3, 296.05),
                                                                    (34, 26, 2, 304.08),
                                                                    (49, 39, 2, 57.23),
                                                                    (1, 25, 1, 575.96),
                                                                    (12, 49, 3, 682.14),
                                                                    (15, 48, 1, 491.63),
                                                                    (33, 6, 3, 554.08),
                                                                    (35, 31, 2, 90.64),
                                                                    (45, 14, 3, 320.25),
                                                                    (14, 33, 2, 106.38),
                                                                    (36, 32, 1, 474.15),
                                                                    (51, 47, 3, 119.57),
                                                                    (42, 40, 1, 160.93),
                                                                    (47, 13, 1, 348.28),
                                                                    (18, 35, 2, 416.05),
                                                                    (34, 37, 2, 561.07),
                                                                    (14, 7, 2, 325.15),
                                                                    (6, 37, 3, 238.09),
                                                                    (5, 35, 1, 658.46),
                                                                    (12, 12, 3, 256.62),
                                                                    (28, 36, 3, 130.65),
                                                                    (25, 39, 3, 403.37),
                                                                    (22, 29, 2, 588.65),
                                                                    (27, 10, 2, 357.57),
                                                                    (3, 19, 2, 215.15),
                                                                    (44, 10, 2, 71.95),
                                                                    (8, 31, 3, 355.26),
                                                                    (3, 2, 1, 200.84),
                                                                    (46, 43, 1, 567.07),
                                                                    (1, 27, 3, 653.33);



SELECT u.id,
       u.name as user_name,
       p.name as product_name,
       p.description,
       p.price,
       p.stock,
       o.status,
       o.created_at
FROM users u
         LEFT JOIN orders o
                   ON u.id = o.user_id
         LEFT JOIN order_items oi
                   ON o.id = oi.order_id
         LEFT JOIN products p
                   ON oi.product_id = p.id
WHERE 1=1
  and o.id is not null
  and oi.id is not null;

